# Generated by Django 5.2.3 on 2025-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('student_grade', models.CharField(choices=[('1KG', '1 Kindergarten'), ('2KG', '2 Kindergarten'), ('1PR', '1 Primary'), ('2PR', '2 Primary'), ('3PR', '3 Primary'), ('4PR', '4 Primary'), ('5PR', '5 Primary'), ('6PR', '6 Primary'), ('1PA', '1 Preparatory'), ('2PA', '2 Preparatory'), ('3PA', '3 Preparatory')], max_length=3)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
